###### Path do your MPV executable
mpv_path: "C:\\Program Files\\mpv\\mpv.exe"

###### Eleven Labs Settings
default_voice: michael
stability: 0.3
similarity_boost: 0.9
style: 0.0
use_speaker_boost: True
xi_key_file_name: elevenlabs_api.key

###### Voice Input Settings
override_wake_word: computer
use_wake_word: True

###### ChatGPT Settings
gpt_key_file_name: chatgpt_api.key
# gpt_key_file_name: chatgpt_api.guest.key
chat_temperature: 1
max_tokens: 100

# Input: $3 / 100k -- Output: $6 / 100k
# chat_model: gpt-4

# Input: $1 / 100k -- Output: $3 / 100k
chat_model: gpt-4-turbo-preview

# Input: $1 / 100k -- Output: $3 / 100k
# chat_model: gpt-4-vision-preview

# Input: $0.05 / 100k -- Output: $0.15 / 100k
# chat_model: gpt-3.5-turbo

# Options: text / voice
chat_input_mode: voice

# Options: text / voice
chat_output_mode: voice

context_dir: ./contexts
default_context_file: default_context.txt
